### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by sahibjotsaggu** [mom0tomo/dotfiles#1]
I've followed the steps in the README.md and I get the following output:
```
# sahibjot at Sahibjots-MacBook-Pro.local in ~/dotfiles on git:master ● [12:02:02]
→ sh ~/dotfiles/setup.sh
ln: /Users/sahibjot/.vimrc: File exists
ln: /Users/sahibjot/.zshrc: File exists
ln: /Users/sahibjot/.zshenv: File exists
ln: /Users/sahibjot/.gitconfig: File exists
ln: /Users/sahibjot/.gitignore: File exists
ln: /Users/sahibjot/.vim/colors/monokai.vim: File exists
```

However, I'm not seeing any changes to my Vim editor. Is there something I'm missing?

**Comment by mom0tomo** [comment]
Sorry for confusing you.

I use this repository only for private, and offten make destructive changes to it.
And I may rewrite Readme in the future,  but now I recommend to use only the scripts of each files.

Thanks for letting me know.
